name: Generate Weekly Contribution Graph

on:
  schedule:
    # Runs every Sunday at 00:00 UTC (once every week)
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Contribution Terrain
        uses: eshahhh/contribution-terrain@v1.0.0
        with:
          username: ${{ github.repository_owner }}
          style: graph
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add graph-eshahhh.svg
          git commit -m "Update weekly contribution graph" || exit 0
          git push